### ISSUE TITLE
Dependency version mismatch for AWS libs

### ISSUE THREAD

**Issue by ericluria** [flowcommerce/dependency#115]
In [delta](https://github.com/flowcommerce/delta/blob/master/build.sbt#L9), the AWS version is currently set to `1.11.313`. In [dependency/delta](https://dependency.flow.io/projects/prj-20161007-350511189), all of the AWS libs have a recommended version of `1.11.315`, except `com.amazonaws.aws-java-sdk-elasticloadbalancing` which has a recommended version of `1.11.314` (despite being a `1.11.315` available).

![screen shot 2018-04-25 at 10 12 39 am](https://user-images.githubusercontent.com/12697797/39251968-91c6e04a-4872-11e8-8657-b740246f4d58.png)

Furthermore, `dependency` shows that the resolver is http://jcenter.bintray.com/, but I'm unable to find any of the AWS libs when searching Bintray.

**Comment by kubukoz** [comment]
I think all AWS libs are on 1.11.361 now, can we close this @ericluria?

**Comment by ericluria** [comment]
yep lgtm
